modif test

diff --git a/toolbox/cmd/bing-ip2hosts b/toolbox/cmd/bing-ip2hosts
--- a/toolbox/cmd/bing-ip2hosts
+++ b/toolbox/cmd/bing-ip2hosts
@@ -1,149 +1,102 @@
 #!/bin/bash
 # bing-ip2hosts - Enumerate hostnames from Bing.com for an IP address.
-# Bing.com is Microsoft's search engine which has an IP: search parameter.
-#
-# By Andrew Horton aka urbanadventurer, MorningStar Security
-# Homepage: http://www.morningstarsecurity.com/research/bing-ip2hosts
-#
-# Version 0.4 Released December 19th, 2013. Updated to use nslookup, new usage, fixed tmp file issue
-# Version 0.3 Released September 21st, 2012. Updated because Bing mobile search changed.
-# Version 0.2 Released April 2nd, 2010
-# Version 0.1 Released December 2nd, 2009 at Kiwicon III in New Zealand
-#
-# License: GPLv3
 
-VERSION=o.4
-TMPDIR=/tmp
+VERSION="0.5"
+TMPDIR="/tmp"
 ANIMATION=1
 OUTPUTIP=0
 HTTPPREFIX=0
-IP=
-PREFIX=
 DEBUG=0
 
-if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-echo -en '\E[31m'
-echo -e "bing-ip2hosts ($VERSION) by Andrew Horton aka urbanadventurer
-Homepage: http://www.morningstarsecurity.com/research/bing-ip2hosts
-"
-echo -en '\033[0m'
-
-echo -e "Useful for web intelligence and attack surface mapping of vhosts during
-penetration tests. Find hostnames that share an IP address with your target 
-which can be a hostname or an IP address.  This makes use of Microsoft 
-Bing.com ability to seach by IP address, e.g. \"IP:210.48.71.196\".
-
-Usage: $0 [OPTIONS] <IP|hostname>
-
-OPTIONS are:
--n\t\tTurn off the progress indicator animation
--t <DIR>\tUse this directory instead of /tmp. The directory must exist.
--i\t\tOptional CSV output. Outputs the IP and hostname on each line, separated by a comma.
--p\t\tOptional http:// prefix output. Useful for right-clicking in the shell.
-"
-exit 1
+if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
+    echo -e "\033[31mbing-ip2hosts ($VERSION) by Andrew Horton aka urbanadventurer\033[0m"
+    echo -e "Homepage: http://www.morningstarsecurity.com/research/bing-ip2hosts\n"
+    echo -e "Usage: $0 [OPTIONS] <IP|hostname>\n"
+    echo -e "OPTIONS are:"
+    echo -e "-n\t\tTurn off the progress indicator animation"
+    echo -e "-t <DIR>\tUse this directory instead of /tmp. The directory must exist."
+    echo -e "-i\t\tOptional CSV output. Outputs the IP and hostname on each line, separated by a comma."
+    echo -e "-p\t\tOptional http:// prefix output. Useful for right-clicking in the shell."
+    exit 1
 fi
 
-while getopts "nipt:" optionName; do
-    case "$optionName" in
-     	 n) ANIMATION=0;;
-	 t) TMPDIR="$OPTARG";;
-	 i) OUTPUTIP=1;;
-	 p) HTTPPREFIX=1;;
-	 [?]) echo "Error"; exit 1;;
+while getopts "nipt:" opt; do
+    case "$opt" in
+        n) ANIMATION=0;;
+        t) TMPDIR="$OPTARG";;
+        i) OUTPUTIP=1;;
+        p) HTTPPREFIX=1;;
+        ?) echo "Error"; exit 1;;
     esac
 done
 
-shift $(($OPTIND -1))
+shift $((OPTIND-1))
 
-if [ -z "$1" ]; then
- echo "need an IP or hostname"
- exit 1
+if [[ -z "$1" ]]; then
+    echo "Error: need an IP or hostname"
+    exit 1
 fi
 
-animation="/-\|"
-page=0
-last_page_check=
-how_many=1
-uniq_hosts=0
-single_page=
-
-# if the parameter looks like an IP go ahead, otherwise resolve it
-if [ `echo "$1" | egrep  "(([0-9]+\.){3}[0-9]+)|\[[a-f0-9:]+\]"`  ]; then
- IP="$1"
+# Check and resolve IP
+if [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ || "$1" =~ \[[a-f0-9:]+\] ]]; then
+    IP="$1"
 else
-# IP=`resolveip -s "$1"`
- IP=`nslookup "$1" |egrep "^Address: \w+\.\w+\.\w+\.\w+$"|tail -1|awk '{ print $2 }'`
- #  dig -t a treshna.com  +short
- if [ "$IP" == "" ]; then
- 	echo "Error: cannot resolve $1 to an IP"
-	exit
- fi
+    IP=$(nslookup "$1" 2>/dev/null | awk '/^Address: / { print $2 }' | tail -1)
+    if [[ -z "$IP" ]]; then
+        echo "Error: cannot resolve $1 to an IP"
+        exit 1
+    fi
 fi
 
-all_hosts=`mktemp -p $TMPDIR -t bing-ip2hosts.tmp.XXXXXX`
+all_hosts=$(mktemp -p "$TMPDIR" -t bing-ip2hosts.XXXXXX)
+page=0
+uniq_hosts=0
+animation="|/-\\"
 
-while [ -z "$last_page_check" ] && [ -n "$how_many" ] && [ -z "$single_page" ]; do
- if [ $ANIMATION == 1 ]; then
-  echo -ne "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
-  echo -en "[ $IP | Scraping $how_many | Found $uniq_hosts | ${animation: $(( $page % 4 )) :1} ]"
- fi
- url="http://www.bing.com/search?q=ip%3A$IP&go=&qs=n&first=${page}0&FORM=PERE"
+while :; do
+    if [[ $ANIMATION -eq 1 ]]; then
+        printf "\r[ $IP | Scraping Page $((page + 1)) | Found $uniq_hosts | ${animation:page%4:1} ]"
+    fi
+    url="http://www.bing.com/search?q=ip%3A$IP&first=${page}0&FORM=PERE"
+    out=$(mktemp -p "$TMPDIR" -t bing-ip2hosts-out.XXXXXX)
+    curl -s "$url" -o "$out"
 
- out=`mktemp -p "$TMPDIR" -t bing-ip2hosts.tmp.XXXXXX`
- wget -q -O "$out" "$url"
+    # Process results and determine if there is a next page
+    how_many=$(grep -oP '<span class="sb_count" id="count">[^<]+' "$out" | cut -d '>' -f 2 | cut -d ' ' -f 1-3)
 
- last_page_check=`egrep -o '<span class="sb_count" id="count">[0-9]+-([0-9]+) of (\1)' $out`
- if [ "$DEBUG" -eq 1 ]; then
-  echo "Last Page Check: $last_page_check"
- fi
+    if [[ -z "$how_many" ]]; then
+        break
+    fi
 
- # if no results are found, how_many is empty and the loop will exit
- how_many=`egrep -o '<span class="sb_count" id="count">[^<]+' $out|cut -d '>' -f 2|cut -d ' ' -f 1-3`
+    # Extract and store hosts
+    grep -oP "<h3><a href=\"[^\"]+" "$out" | cut -d '"' -f 2 | tee -a "$all_hosts"
 
- # check for a single page of results
- single_page=`egrep -o '<span class="sb_count" id="count">[0-9] results' $out`
- if [ $DEBUG -eq 1 ];then
-  echo "Single Page: $single_page"
- fi
+    # Update unique hosts count
+    uniq_hosts=$(cut -d '/' -f 3 < "$all_hosts" | tr '[:upper:]' '[:lower:]' | sort | uniq | wc -l)
 
- # no captcha support or detection
- # pages will contain "Typing the characters in the picture above helps us ensure that a person, not a program, is performing a search"
+    ((page++))
+    if [[ $DEBUG -eq 1 ]]; then
+        echo "Page: $page"
+    fi
 
- vhosts=`cat "$out"| egrep -o "<h3><a href=\"[^\"]+" $out |cut -d '"' -f 2`
- echo -e "$vhosts" >> "$all_hosts"
-
- uniq_hosts=`cat "$all_hosts" | cut -d '/' -f 3 | tr '[:upper:]' '[:lower:]' | sort | uniq | wc -l`
-
- if [ $DEBUG -eq 0 ]; then
-  rm -f "$out"
- fi
- 
- let page=$page+1 
- if [ $DEBUG -eq 1 ]; then
-  echo "Page: $page"
- fi
+    # Cleanup the temporary output file
+    rm -f "$out"
 done
 
-if [ $ANIMATION == 1 ]; then
-	echo
+if [[ $ANIMATION -eq 1 ]]; then
+    echo
 fi
 
-uniq_hosts=`cat "$all_hosts" | cut -d '/' -f 3 | tr '[:upper:]' '[:lower:]' | sort | uniq`
+# Final processing of unique hosts
+uniq_hosts=$(cut -d '/' -f 3 < "$all_hosts" | tr '[:upper:]' '[:lower:]' | sort | uniq)
 
-if [ $DEBUG -eq 0 ]; then
-  rm -f "$all_hosts"
-fi
+# Cleanup the main temporary file
+rm -f "$all_hosts"
 
-if [ $OUTPUTIP == 1 ]; then
-	PREFIX="$IP,"
-fi
-if [ $HTTPPREFIX == 1 ]; then
-	PREFIX="$PREFIX""http://"
-fi
+PREFIX=""
+[[ $OUTPUTIP -eq 1 ]] && PREFIX="$IP,"
+[[ $HTTPPREFIX -eq 1 ]] && PREFIX="http://${PREFIX}"
 
-for h in `echo "$uniq_hosts"`
-do
-	echo "$PREFIX$h"
+for h in $uniq_hosts; do
+    echo "${PREFIX}${h}"
 done
-
